### ISSUE TITLE
vod variable ivy-hooks-alist？

### ISSUE THREAD

**Issue by peng051410** [with-emacs/mcfly#2]
When eval buffer, I got this error:
`Debugger entered--Lisp error: (void-variable ivy-hooks-alist)
  (cons (cons 'swiper 'mcfly-swiper) ivy-hooks-alist)
  (setq ivy-hooks-alist (cons (cons 'swiper 'mcfly-swiper) ivy-hooks-alist))
  (lambda nil (setq ivy-hooks-alist (cons (cons 'swiper 'mcfly-swiper) ivy-hooks-alist)) (defalias 'mcfly-swiper (function (lambda nil (let ((sym (let ((save-selected-window--state (internal--before-with-selected-window (ivy--get-window ivy-last)))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) 'norecord) (thing-at-point 'symbol)) (internal--after-with-selected-window save-selected-window--state)))))) (if sym (progn (add-hook 'pre-command-hook 'mcfly-back-to-present nil t) (save-excursion (insert (propertize sym 'face 'shadow))))))))))()
  eval-after-load(ivy (lambda nil (setq ivy-hooks-alist (cons (cons 'swiper 'mcfly-swiper) ivy-hooks-alist)) (defalias 'mcfly-swiper (function (lambda nil (let ((sym (let ((save-selected-window--state (internal--before-with-selected-window (ivy--get-window ivy-last)))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) 'norecord) (thing-at-point 'symbol)) (internal--after-with-selected-window save-selected-window--state)))))) (if sym (progn (add-hook 'pre-command-hook 'mcfly-back-to-present nil t) (save-excursion (insert (propertize sym 'face 'shadow)))))))))))
  eval-buffer()  ; Reading at buffer position 1723
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer nil nil)
  command-execute(eval-buffer)`

What should i do?

**Comment by clemera** [comment]
It looks like the variable `ivy-hooks-alist` is unknown:

    (void-variable ivy-hooks-alist)

What version of `ivy` are you using? You probably need to update it.

**Comment by peng051410** [comment]
version is 20180415.905, it's to old?

**Comment by clemera** [comment]
I think so, what does `C-h v ivy-hooks-alist` show you? When this variable isn't defined you need to update.

**Comment by peng051410** [comment]
Yes, my ivy version problem!
